### PR TITLE
Resolved Issue #31. Removed users' ability to move non-aces into empt…

### PR DESCRIPTION
**Pull request by terri-hewitt**
…y columns.

### CODE REVIEW

**Comment by Lucas-Campos-Davis** [comment]
Everything looks good to me, one suggestion:
Use the link below to make the error box have the error symbol. 
https://docs.oracle.com/javase/tutorial/uiswing/components/dialog.html#features

**Comment by terri-hewitt** [comment]
Good idea! I'll change that.

**Comment by cairnsr** [comment]
Looks great, might want to try and change the error title so its more specific. Such as having the title state "Invalid Move" instead of just error.

**Comment by terri-hewitt** [comment]
I like that idea. That'll definitely make it a little cleaner looking.

**Pull request merged**
