### PR TITLE
Added a deck class

### PR DESCRIPTION
**Pull request by Lucas-Campos-Davis**
I Have added a deck class

### CODE REVIEW

**Comment by terri-hewitt** [comment]
In Game.java on line 13, to initialize an instance of a deck, use: Deck d = new Deck(). See line 35 in ApplicationController.java for a good example of how to do this.

**Comment by Lucas-Campos-Davis** [comment]
Good catch! will do

**Comment by Lucas-Campos-Davis** [comment]
It's been updated now

**Comment by terri-hewitt** [comment]
Awesome, I'll go ahead and merge the changes.

**Pull request merged**
